version: '3.8'

services:
  image-service:
    container_name: image-processing-service
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: yarn start
    #restart: always